### ISSUE TITLE
Add ability to re-sign WADs from retail->dev and dev->retail

### ISSUE THREAD

**Issue by InternalLoss** [GerbilSoft/rvthtool#4]
Your own words:

It's basically the same sort of thing as what rvthtool does when importing e.g. retail discs to debug systems
http://wiibrew.org/wiki/WAD_files
WAD contains a header, cert chain, ticket, TMD
Data can be ignored
to convert retail to debug, you have to do the following
1. replace the certificate chain with the debug certs (this may require adjusting offsets; not sure)
2. in the ticket: http://wiibrew.org/wiki/Ticket
Ticket
a. decrypt the key using the appropriate retail key
b. re-encrypt the key using the debug common key
c. re-sign the ticket using the debug private keys

3. in the TMD: http://wiibrew.org/wiki/Tmd_file_structure
Tmd file structure
a. re-sign the ticket using the debug private keys
that's it

**Comment by InternalLoss** [comment]
👀

**Comment by GerbilSoft** [comment]
Merged in commit 2e3a32648772800fc6f6fc57d8ebd37699374292.
